### ISSUE TITLE
white

### ISSUE THREAD

**Issue by c0b21055** [c0b21125/ProjExD#4]
https://github.com/c0b21125/ProjExD/blob/df9935741822f13dbf4c94b8f622d262cd016d6b/ex02/calc.py#L54

もとから電卓の色は白なので、whiteを書く必要性があるのかが普通に疑問に思いました。
そのほかは簡潔できれいだと思います。

**Comment by c0b21125** [comment]
コメントありがとうございます。
デフォルトの色が灰色で字が見えにくかったため白色に変更しました。
