### ISSUE TITLE
表示改善の為の修正

### ISSUE THREAD

**Issue by pipopixu** [c0b21125/ProjExD#5]
https://github.com/c0b21125/ProjExD/blob/2bcab9fae96a1b4495c80bafbe641b5ab972ec63/ex02/calc.py#L57

数字と四則演算の改行をi%=3としたうえで、その他(ACや％など)のbtn.grid(row=r, column=c)について、row=r-2,column=c+1などの形にすると表示された時に綺麗にみえると思います。

**Comment by c0b21125** [comment]
コメントありがとうございます！！電卓のレイアウト（ボタンの位置）のコードが分からず困っていたため非常に助かりました！
